# Generated by Django 3.1.7 on 2021-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('important', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.CharField(max_length=100)),
            ],
        ),
    ]
