# Generated by Django 3.1.7 on 2021-04-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file_upload',
        ),
    ]
